config/routes.rb
Rails.application.routes.draw do

  root to: 'businesses#index'

  get '/show_json', to: 'businesses#show_json'

  get '/login', to: 'sessions#new'

  get 'logout' => 'sessions#destroy'

  get '/moresongs' => 'songs#more_songs_by_artist'

  get 'badurl' => 'sessions#badurl'

  resources :sessions

  get '/auth/spotify/callback' => 'businesses#spotify_user'

  resources :locations do
    resources :playlists, :only => [:show]
  end

  resources :businesses do
    resources :locations, :only => [:create, :index, :new, :show, :destroy, :edit, :update]
    resources :playlists, :only => [:show, :index]
  end

  resources :playlists do
    resources :songs, :only => [:destroy]
  end

  get "/playlists/:playlist_id/songs/:song_id" => "songs#destroy"

  get '*path', to: redirect('/badurl')

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  before_action :require_login, except: [:spotify_user, :new, :create]

  def index
    if @business = Business.find_by(id: session[:business_id])
      render :show
    else
      redirect_to badurl_path
    end
  end

  def spotify_user
    spotify_user = RSpotify::User.new(auth) #retreives spotify users info

    if !session[:business_id] && !Business.find_by(uid: spotify_user.id) #if user is not logged and doesn't have an account already
      @business = Business.create(email_address: spotify_user.email) do |b| #creates new business object using spotify id
        b.uid = spotify_user.id #sets uid as spotify user id so later i can extend this app to allow for playback
        b.password = SecureRandom.urlsafe_base64 #generates a random password for spotify strategy
        b.name = spotify_user.display_name #sets name
      end
      session[:business_id] = @business.id
      build_playlists(@business)
      @business.save
      redirect_to business_path(@business)
    elsif !session[:business_id] && Business.find_by(uid: spotify_user.id) #user not logged in but they do have a spotify account linked to worknplay
      @business = Business.find_by(uid: spotify_user.id)
      session[:business_id] = @business.id
      redirect_to business_path(@business)
    elsif Business.find_by(id: session[:business_id]).uid == nil #if no spotify account is connected yet to current account
      if Business.find_by(uid: spotify_user.id)
        flash[:notice] = "Sorry, it looks like another user is already using that spotify account. Be sure to log out of that spotify account in any of your current browser windows in order to proceed."
        @business = Business.find_by(id: session[:business_id])
        redirect_to business_playlists_path(@business)
      else
        @business = Business.find_by(id: session[:business_id])
        @business.uid = spotify_user.id
        build_playlists(@business)
        @business.save
        redirect_to business_playlists_path(@business)
      end
    end
  end

  def new
    if @business = Business.find_by(id: session[:business_id])
      redirect_to business_path(@business)
    else
      @business = Business.new
    end
  end

  def create
    @business = Business.new(business_params)
    if @business.save
      session[:business_id] = @business.id
      redirect_to business_path(@business)
    else
      render :new
    end
  end


  def show
    if params[:business_id] == Business.find_by(id: session[:business_id]).id #ensures
      @business = Business.find_by(id: session[:business_id])
      @location = Location.new
    else
      redirect_to root_path
    end
  end

  def show_json
    @business = Business.find_by(id: session[:business_id])
    respond_to do |f|
      f.json {render json: @business}
    end
  end

  private

  def business_params
    params.require(:business).permit(:name, :email_address, :password, :password_confirmation)
  end

  def auth
    # binding.pry
    request.env['omniauth.auth']
  end

  def build_playlists(business)
    RSpotify::User.new(auth).playlists.each do |playlist| #begins iteration over each of spotify_user's playlist objects and
      s_playlist = Playlist.find_or_create_by(name: playlist.name.to_s) #creates a new Playlist for each object
      s_playlist.business = business #associates the Playlist with the business
      s_playlist.save #saves the Playlist object
        playlist.tracks.each do |track| #iterates over each track in the playlist
          song = Song.find_or_create_by(name: track.name, artist: track.artists.first.name, track_id: track.id) #creates a new Song object for each track in the playlist
          song.playlist = s_playlist #saves the song in the newly created playlist object
          s_playlist.songs << song #saves the song in the newly created playlist object
          s_playlist.save #saves the playlist
        end
      end
  end

end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/new.html.erb
<h1>Sign Up For Work And Play here:</h1>

<% if @business.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@business.errors.count, "error") %>
      caused an issue:
    </h2>

    <ul>
    <% @business.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= flash[:notice] %>

<%= form_for @business, :html => {:class => "form-group"} do |f| %>
  <%= f.label(:name, "Business name:")%>
  <%= f.text_field :name, class: "form-control" %><br />
  <%= f.label(:email_address, "Email Address:")%>
  <%= f.text_field :email_address, class: "form-control" %><br />
  <%= f.label(:password, "Choose a password:")%>
  <%= f.password_field :password, class: "form-control" %><br />
  <%= f.label(:password_confirmation, "Confirm your password:")%>
  <%= f.password_field :password_confirmation, class: "form-control" %><br />
  <%= f.submit "Create Your Account", class: "btn btn-default" %>
<% end %>

<br />

<%= link_to('Sign Up With Spotify', '/auth/spotify') %><br /><br />
<%= link_to('Already have an account? Sign in here', login_path) %>

app/views/businesses/show.html.erb
<h1>Hello <%= @business.name %> </h1>
<% if flash[:notice] %>
  <%= flash[:notice] %><br />
<p>
  Check out your <%= link_to("locations", business_locations_path(@business)) %> and <%= link_to("playlists", business_playlists_path(@business)) %>
</p>

<% else %>

  <p>Welcome to WorkandPlay, the background-music app for your business!</p>

  <% if @business.locations.count == 0 %>
    <p>
      To get started, <%= link_to("add your first location", new_business_location_path(@business)) %>
    </p>
  <% else %>
    <p>
      Check out your <%= link_to("locations", business_locations_path(@business)) %> and <%= link_to("playlists", business_playlists_path(@business), id: "my-music2") %>
    </p>
  <% end %>
<% end %>