config/routes.rb
Rails.application.routes.draw do

  root to: 'businesses#index'

  get '/show_json', to: 'businesses#show_json'

  get '/login', to: 'sessions#new'

  get 'logout' => 'sessions#destroy'

  get '/moresongs' => 'songs#more_songs_by_artist'

  get 'badurl' => 'sessions#badurl'

  resources :sessions

  get '/auth/spotify/callback' => 'businesses#spotify_user'

  resources :locations do
    resources :playlists, :only => [:show]
  end

  resources :businesses do
    resources :locations, :only => [:create, :index, :new, :show, :destroy, :edit, :update]
    resources :playlists, :only => [:show, :index]
  end

  resources :playlists do
    resources :songs, :only => [:destroy]
  end

  get "/playlists/:playlist_id/songs/:song_id" => "songs#destroy"

  get '*path', to: redirect('/badurl')

end

app/models/business.rb
class Business < ApplicationRecord
  validates :email_address, presence: true
  validates :email_address, uniqueness: true
  validates :email_address, format: { with: URI::MailTo::EMAIL_REGEXP }
  has_secure_password
  has_many :locations
  has_many :playlists
  #
  def to_param
    "#{id} #{name}".parameterize
  end
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :business
  has_many :location_playlists
  has_many :locations, through: :location_playlists
  has_many :songs
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :require_login, :set_business, except: [:show]

  def index
    @location = Location.find_by(id: params[:location_id])
    @playlists = @business.playlists.all
    respond_to do |f|
      f.html
      f.json {render json: @playlists}
    end
  end


  def show
    @business = Business.find_by(id: session[:business_id])
    if params[:location_id] #deals with different URLS - location_playlist or business_playlist
      @location = Location.find_by(id: params[:location_id])
      @playlist = Playlist.find_by(id: params[:id])
    else
      @playlist = Playlist.find_by(id: params[:id])
      respond_to do |f|
        f.html
        f.json {render json: @playlist}
      end
    end
  end

  private

  def set_business
    if params[:business_id].to_i == session[:business_id]
      @business = Business.find_by(id: params[:business_id])
    else
      redirect_to badurl_path
    end
  end


end

app/helpers/playlists_helper.rb
module PlaylistsHelper

  def playlist_times
    ["6am-9am", "9am-12pm", "12pm-3pm", "3pm-6pm", "6pm-9pm"]
  end

  def playlist_schedule(location)
    location.playlists.each_with_index do |playlist, index|
      concat(content_tag :h4, "#{playlist_times[index]}").concat(link_to(playlist.name, location_playlist_path(location, playlist))).concat(content_tag(:br))
    end.join("\n").html_safe
  end

end

app/views/playlists/_locationplaylist_energy_select.html.erb
<%= radio_button_tag("energy_level#{location_playlist_index}", "Low") %>
<%= label_tag(:energy_low, "Low") %>
<%= radio_button_tag("energy_level#{location_playlist_index}", "Medium") %>
<%= label_tag(:energy_medium, "Medium") %>
<%= radio_button_tag("energy_level#{location_playlist_index}", "High") %>
<%= label_tag(:energy_high, "High") %>

app/views/playlists/_playlist_select.html.erb
<%= collection_select :playlist_ids, :id, @business.playlists.all, :id, :name, { :selected => Playlist.find_by(id: playlist_variable) ? Playlist.find_by(id: playlist_variable).id : nil }, {:name => 'location[playlist_ids][]'}%><br />

app/views/playlists/index.html.erb
<h1><%= @business.name %>'s Music</h1>

<div class = "container">
  <% @playlists.each do |playlist| %>
    <h3><%=link_to(playlist.name, business_playlist_path(@business, playlist), class: "playlist")%></h3>
    <p id="playlist-<%= playlist.id %>"></p>
  <% end %>
</div>
<% if @business.uid.blank? %>
<div class = "container">
  <%= flash[:notice] %><br /><br />
  <%= link_to('Connect your spotify account to import your playlists', '/auth/spotify') %>
</div>
<% end %>

app/views/playlists/show.html.erb
<h3><%= @playlist.name %></h3>
<% if @playlist.songs.count == 0 %>
  <p>
    Oh no! This playlist seems to be empty. You can <%= button_to('delete', location_playlist_path(@location, @playlist), method: :delete) %> this playlist or simply <%= link_to('schedule', edit_location_path(@location, @playlist)) %> a different one.
  </p>
<% else %>
  <% @playlist.songs.each do |song| %>
  <div class="container">
     <%= song.artist %> - <%= song.name %><br />
     <%= link_to('Remove', playlist_song_path(@playlist, song), method: :delete) %>
  </div>
  <% end %>
  <% if @location %>
  <p>
    Want to change it up? Simply remove songs or <%= link_to('schedule', edit_location_path(@location, @playlist)) %> a different playlist.
  </p>
  <% else %>
  <p>
    Don't like that song? Simply remove it!
  </p>
  <% end %>
  <% end %>
  <%=link_to("Back To Your Playlists", business_playlists_path(@business)) %>