config/routes.rb
Rails.application.routes.draw do

  root to: 'businesses#index'

  get '/show_json', to: 'businesses#show_json'

  get '/login', to: 'sessions#new'

  get 'logout' => 'sessions#destroy'

  get '/moresongs' => 'songs#more_songs_by_artist'

  get 'badurl' => 'sessions#badurl'

  resources :sessions

  get '/auth/spotify/callback' => 'businesses#spotify_user'

  resources :locations do
    resources :playlists, :only => [:show]
  end

  resources :businesses do
    resources :locations, :only => [:create, :index, :new, :show, :destroy, :edit, :update]
    resources :playlists, :only => [:show, :index]
  end

  resources :playlists do
    resources :songs, :only => [:destroy]
  end

  get "/playlists/:playlist_id/songs/:song_id" => "songs#destroy"

  get '*path', to: redirect('/badurl')

end

app/models/location.rb
class Location < ApplicationRecord
  validates :address, presence: true
  validates :address, uniqueness: true
  validates :name, presence: true
  belongs_to :business
  has_many :location_playlists
  has_many :playlists, through: :location_playlists
  accepts_nested_attributes_for :playlists #redundant as im not using fields_for

  def self.by_state(state) #use scope method!
    where(state: state)
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :require_login, :set_business, except: [:create]

  def index
    if params[:state] == "All Locations"
      @locations = @business.locations.all
    elsif !params[:state].blank?
      @locations = @business.locations.by_state(params[:state])
    else
      @locations = @business.locations.all
    end
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      render json: @location
    else
      render :new #renders with error messages
    end
  end

  def show
    @location = Location.find_by(id: params[:id])
    respond_to do |f|
      f.html
      f.json {render json: @location}
    end
  end

  def edit
    @location = Location.find_by(id: params[:id])
  end

  def update
    @location = Location.find(params[:id])
    @location.update(location_params)
    set_energy_levels(@location)
    redirect_to business_location_path(@business, @location)
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to root_path
  end

  private

  def set_business
    if params[:state]
      @business = Business.find_by(id: session[:business_id])
    elsif params[:business_id].to_i == session[:business_id]
      @business = Business.find_by(id: params[:business_id])
    else
      redirect_to badurl_path
    end
  end

  def set_energy_levels(location) # this is really bad and should definitely be in the model
    count = 0
    LocationPlaylist.all.each do |locationplaylist|
      if locationplaylist.location_id == location.id
        locationplaylist.energy = eval("params[:energy_level#{count}]")
        locationplaylist.save
        count += 1
      end
    end
  end

  def location_params
    params.require(:location).permit(:name, :address, :state, :business_id, :energy_level0, :energy_level1, :energy_level2, :energy_level3, :energy_level4, :playlist_ids => [])
  end

end

app/helpers/locations_helper.rb
module LocationsHelper

  def us_states_for_location_creation
    [ ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
      ]
  end

  def us_states_for_search
    [ ['All Locations'],
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
      ]
  end

end

app/views/locations/edit.html.erb
<h1><%= @location.name %></h1>
<p> Schedule your playlists and choose their energy levels for this location </p>
<% if @business.uid %>
  <%= form_tag(business_location_path(@business, @location), method: :patch) do %>

    <h3>6am - 9am</h3>
    <%= render 'playlists/playlist_select', :playlist_variable => @location.playlists[0] %>
    <%= render 'playlists/locationplaylist_energy_select', :location_playlist_index => 0 %>


    <h3>9am - 12noon</h3>
    <%= render 'playlists/playlist_select', :playlist_variable => @location.playlists[1] %>
    <%= render 'playlists/locationplaylist_energy_select', :location_playlist_index => 1 %>

    <h3>12noon - 3pm</h3>
    <%= render 'playlists/playlist_select', :playlist_variable => @location.playlists[2] %>
    <%= render 'playlists/locationplaylist_energy_select', :location_playlist_index => 2 %>

    <h3>3pm - 6pm</h3>
    <%= render 'playlists/playlist_select', :playlist_variable => @location.playlists[3] %>
    <%= render 'playlists/locationplaylist_energy_select', :location_playlist_index => 3 %>

    <h3>6pm - 9pm</h3>
    <%= render 'playlists/playlist_select', :playlist_variable => @location.playlists[4] %>
    <%= render 'playlists/locationplaylist_energy_select', :location_playlist_index => 4 %>

    <br />

    <%= submit_tag "schedule playlists" %>
  <% end %>
<% else %>
  <%= link_to('Connect your spotify account to schedule playlists', '/auth/spotify') %>
<% end %>

app/views/locations/index.html.erb
<p>Filter locations by state</p>
<%= form_tag("/locations", method: "get") do %>
  <%= select_tag :state, options_for_select(us_states_for_search), include_blank: true %>
  <%= submit_tag "Filter" %>
<% end %>

<% @locations.each do |location| %>
  <div >
    <h3><%= link_to location.name, business_location_path(@business, location), class: "location" %></h3>
    <div id="location-<%=location.id.to_s%>">

    </div>
    <p ><%= location.address %>, <%= location.state %></p>
  </div>
<% end %>

<%= link_to "Add a new location", new_business_location_path(@business) %>

app/views/locations/new.html.erb
<% if @location.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@location.errors.count, "error") %>
      prohibited this business from being saved:
    </h2>

    <ul>
    <% @location.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<h1>Add a new location:</h1>
<%= form_for ([@business, @location]), :html => {:class => "form-group"} do |f|%>
  <%= f.label(:name, "Location name:")%>
  <%= f.text_field :name, class: "form-control" %><br />
  <%= f.label(:address, "Street address:")%>
  <%= f.text_area :address, class: "form-control" %><br />
  <%= f.label(:state, "State:")%>
  <%= f.select :state, options_for_select(us_states_for_location_creation), {:prompt => true} %> <br />
  <%= f.hidden_field :business_id, value: @business.id %>
  <%= f.submit "Create New Location", class: "btn btn-default"%>
<% end %>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>

<% if @business.uid && @location.playlists.count > 0 %>
  <h4>Playlists on schedule:</h4>
  <%= playlist_schedule(@location) %><br />

  <%= link_to('Edit playlist schedule', edit_business_location_path(@business, @location)) %><br />

<% elsif @business.uid && @location.playlists.count == 0  %>
  <%= link_to('Schedule some playlists here', edit_business_location_path(@business, @location)) %><br />

<% else %>
  <%= link_to('Connect your spotify account to schedule playlists', '/auth/spotify') %>
<% end %><br /><br />

<%= button_to("Delete this location", business_location_path(@business, @location), method: :delete) %>